syms x              % 声明符号变量x
P=taylor(exp(-x^2),7)  % 求函数exp(-x^2)的6阶Taylor展开式
x1=linspace(0,1);  % 自变量的取值范围
plot(x1,exp(-x1.^2),'k')  % 绘制函数exp(-x^2)的图形
hold on  % 图形保持
P1=inline(P);  % 将符号表示式转换为内联函数
plot(x1,P1(x1),':')  % 绘制函数exp(-x^2)的6阶Taylor展开式函数图形
legend({'$${y_1} = {e^{ - {x^2}}}$$',...
    '$${y_2}=-\frac{{{x^6}}}{6}+\frac{{{x^4}}}{2}-{x^2}+1$$'},...
    'interpreter','latex','fontsize',14,0)  % 添加图例
text(0.5,0.95,['$$\int_0^1 {{y_1}dx}  =$$',...
    char(vpa(int(exp(-x^2),0,1),10)),'...'],...
    'interpreter','latex','fontsize',12)  % 图形标注
text(0.5,0.85,['$$\int_0^1 {{y_2}dx}  =$$',...
    char(vpa(int(P,x,0,1),10))],'interpreter',...
'latex','fontsize',12)  % 图形标注
set(gcf,'Color','w')  % 将图形窗口设为白色

